parameters:
    uploadPath: 'public/assets/images/%env(APP_NAME)%'
    basePath: '/assets/images/%env(APP_NAME)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
